title: Experimental Learn Ubiquity Robots
description: Experimental Tutorials for Magni
email: jrlandau@gmail.com

theme: jekyll-theme-cayman

plugins:
- jekyll-coffeescript
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
